// @vitest-environment jsdom
import React from 'react'
import { webcrypto } from 'node:crypto'
import { beforeEach, afterEach, test, expect, vi } from 'vitest'
import { render, screen, fireEvent, cleanup, waitFor, configure } from '@testing-library/react'
import App from '../src/App'
// Real password derivation can exceed Testing AI Lab's 1s default on busy devices.
configure({ asyncUtilTimeout: 10000 })
vi.setConfig({ testTimeout: 20000 })
vi.mock('../src/brains', async original => ({ ...await original<typeof import('../src/brains')>(), ensureDefaultOfflineBrain: vi.fn().mockResolvedValue({}) }))
vi.mock('../src/translation/package', () => ({ packInstalled: vi.fn().mockResolvedValue(true), PACK_MIB: 611, PACK_URL: '', downloadPack: vi.fn(), installPack: vi.fn() }))
vi.mock('../src/translation/client', () => ({ translateOffline: vi.fn().mockResolvedValue('Translated locally') }))
beforeEach(() => {
  localStorage.clear()
  vi.stubGlobal('crypto', webcrypto)
  vi.stubGlobal('matchMedia', () => ({ matches: true, addEventListener() {}, removeEventListener() {} }))
  vi.stubGlobal('speechSynthesis', { cancel() {}, getVoices: () => [], addEventListener() {}, removeEventListener() {} })
  Element.prototype.scrollTo = vi.fn()
})
afterEach(() => { cleanup(); vi.unstubAllGlobals() })
test('registration, saved chats, sign-out and sign-in form a working local account flow', async () => {
  render(<App />)
  expect(screen.queryByRole('button', { name: 'Chat history' })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Register or sign in' }))
  fireEvent.click(screen.getByRole('button', { name: 'Create an account' }))
  fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'user@user.com' } })
  fireEvent.change(screen.getByLabelText('Password', { exact: true }), { target: { value: 'user123321' } })
  fireEvent.change(screen.getByLabelText('Confirm password'), { target: { value: 'user123321' } })
  fireEvent.click(screen.getByRole('button', { name: 'Create account', exact: true }))
  await screen.findByRole('button', { name: 'Chat history' })
  fireEvent.change(screen.getByRole('textbox', { name: 'Message' }), { target: { value: 'Hello private chat' } })
  fireEvent.submit(document.querySelector('form.composer')!)
  await screen.findByText('Translated locally')
  await screen.findByRole('button', { name: 'Hello private chat' })
  fireEvent.click(screen.getByRole('button', { name: 'Your account' }))
  fireEvent.click(screen.getByRole('button', { name: 'Sign out' }))
  await waitFor(() => expect(screen.queryByRole('button', { name: 'Chat history' })).toBeNull())
  expect(screen.queryByText('Translated locally')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Register or sign in' }))
  fireEvent.change(screen.getByLabelText('Email or username'), { target: { value: 'user@user.com' } })
  fireEvent.change(screen.getByLabelText('Password'), { target: { value: 'user123321' } })
  fireEvent.click(screen.getByRole('button', { name: 'Sign in', exact: true }))
  fireEvent.click(await screen.findByRole('button', { name: 'Hello private chat' }))
  expect(await screen.findByText('Translated locally')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: /New chat/ }))
  expect(screen.queryByText('Translated locally')).toBeNull()
  expect(screen.getByRole('button', { name: 'Hello private chat' })).toBeTruthy()
})
test('guest conversations never write a local account history', async () => {
  render(<App />)
  fireEvent.click(screen.getByRole('button', { name: 'Open chat' }))
  await screen.findByRole('checkbox', { name: 'Offline Translator' })
  fireEvent.change(screen.getByRole('textbox', { name: 'Message' }), { target: { value: 'Guest message' } })
  fireEvent.submit(document.querySelector('form.composer')!)
  await screen.findByText('Translated locally')
  expect(Object.keys(localStorage).filter(key => key.startsWith('rai-account'))).toEqual([])
  cleanup()
  render(<App />)
  expect(screen.queryByText('Guest message')).toBeNull()
})

test('guest continuation requires Agree and Cancel returns to authorization', () => {
  render(<App />)
  fireEvent.click(screen.getByRole('button', { name: 'Register or sign in' }))
  fireEvent.click(screen.getByRole('button', { name: 'Continue as guest' }))
  expect(screen.getByText(/your conversation is temporary/i)).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Cancel', exact: true }))
  expect(screen.getByRole('button', { name: 'Sign in', exact: true })).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Continue as guest' }))
  fireEvent.click(screen.getByRole('button', { name: 'Agree', exact: true }))
  expect(screen.queryByRole('dialog')).toBeNull()
  expect(screen.getByRole('textbox', { name: 'Message' })).toBeTruthy()
  expect(screen.queryByRole('button', { name: 'Chat history' })).toBeNull()
})
test('the requested admin test credentials work through the sign-in form', async () => {
  render(<App />)
  fireEvent.click(screen.getByRole('button', { name: 'Register or sign in' }))
  fireEvent.change(screen.getByLabelText('Email or username'), { target: { value: 'admin' } })
  fireEvent.change(screen.getByLabelText('Password'), { target: { value: 'admin' } })
  fireEvent.click(screen.getByRole('button', { name: 'Sign in', exact: true }))
  await screen.findByRole('button', { name: 'Chat history' })
  expect(screen.getByRole('button', { name: 'Collapse history' })).toBeTruthy()
  expect(screen.queryByRole('button', { name: 'Collapse chat sidebar' })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Minimize chat' }))
  expect(screen.queryByRole('complementary', { name: 'Chat history' })).toBeNull()
  expect(screen.queryByRole('button', { name: 'Expand chat sidebar' })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Open chat' }))
  expect(screen.getByRole('complementary', { name: 'Chat history' })).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Collapse history' }))
  expect(screen.getByRole('button', { name: 'Expand chat sidebar' })).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Close and clear chat' }))
  expect(screen.queryByRole('button', { name: 'Expand chat sidebar' })).toBeNull()
  expect(screen.queryByRole('complementary', { name: 'Chat history' })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Open chat' }))
  expect(screen.queryByRole('complementary', { name: 'Chat history' })).toBeNull()
  expect(screen.getByRole('button', { name: 'Expand chat sidebar' })).toBeTruthy()
  expect(localStorage.getItem('rai-history-expanded')).toBe('false')
  fireEvent.click(screen.getByRole('button', { name: 'Expand chat sidebar' }))
  fireEvent.click(screen.getByRole('button', { name: 'Minimize chat' }))
  fireEvent.click(screen.getByRole('button', { name: 'Open chat' }))
  expect(screen.getByRole('complementary', { name: 'Chat history' })).toBeTruthy()
  expect(localStorage.getItem('rai-history-expanded')).toBe('true')
})
