import { InstallProgress, finishInstallation } from '../components/InstallProgress'
import { useEffect, useRef, useState } from 'react'
import { DESKTOP_MODELS, desktopRequest, desktopStatus, pullDesktopModel, type DesktopStatus } from './desktop'
export function DesktopModels({selectedChat,selectedTranslator,onChange,disabled}:{selectedChat:string;selectedTranslator:string;onChange:(id?:string)=>void;disabled:boolean}) {
 const [status,setStatus]=useState<DesktopStatus>();const [busy,setBusy]=useState('');const [progress,setProgress]=useState('');const [error,setError]=useState('');const controller=useRef<AbortController|null>(null)
 const [finishing,setFinishing]=useState(false)
 const refresh=async()=>{const next=await desktopStatus();setStatus(next);return next}
 useEffect(()=>{void refresh();return()=>controller.current?.abort()},[])
 async function install(id:string) {const abort=new AbortController();controller.current=abort;setBusy(id);setFinishing(false);setProgress('');setError('');try{await pullDesktopModel(id,abort.signal,setProgress);const next=await refresh();if(!next.installed.includes(id))throw new Error('Installation could not be verified.');setFinishing(true);await finishInstallation(abort.signal);onChange(id)}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Installation failed.')}finally{controller.current=null;setFinishing(false);setBusy('')}}
 async function remove(id:string){setBusy(id);setProgress('');setError('');try{await desktopRequest('delete',{model:id});await refresh();onChange()}catch(e){setError(e instanceof Error?e.message:'Deletion failed.')}finally{setBusy('')}}
 return <>{status && !status.available && <p className="modal-help">{status.error} <button className="modal-btn" onClick={()=>void refresh()}>Retry</button></p>}<ul className="side-panel-list offline-models">{DESKTOP_MODELS.map(model=>{
 const installed=status?.installed.includes(model.id);const active=(model.kind==='chat'?selectedChat:selectedTranslator)===model.id
 const supported=status?.available && status.memoryGB>=model.minMemoryGB
 return <li className="side-panel-item" key={model.id}><details className="store-info translator-info"><summary aria-label="NLLB-200 model license">?</summary><div className="translator-info-popover"><strong>Model license</strong><p className="modal-help">Meta NLLB-200 · CC-BY-NC 4.0. For non-commercial use. <a href="https://huggingface.co/facebook/nllb-200-3.3B" target="_blank" rel="noreferrer">Model card and license</a></p></div></details><div className="side-panel-item-body"><span className="side-panel-item-name">{model.name}</span><span className="side-panel-item-meta">{model.kind==='translation'?'Desktop translator · EN, KA, RU':'Offline AI'} · {model.sizeGB} GB · {model.minMemoryGB} GB RAM</span></div><div className="model-actions">{busy===model.id?<><InstallProgress label={finishing?'Installing…':progress||'Working…'} finishing={finishing} />{controller.current&&<button className="modal-btn" onClick={()=>controller.current?.abort()}>Cancel</button>}</>:installed?<>{active?<span className="translator-active-badge">Active</span>:<button className="modal-btn" disabled={disabled||!!busy||!supported} onClick={()=>onChange(model.id)}>Use</button>}<button className="modal-btn danger" disabled={disabled||!!busy} onClick={()=>void remove(model.id)}>Delete</button></>:<button className="modal-btn primary" disabled={disabled||!!busy||!supported} title={status?.available&&!supported?`Requires ${model.minMemoryGB} GB RAM; this computer has ${status.memoryGB} GB.`:undefined} onClick={()=>void install(model.id)}>{status?.available&&!supported?`${model.minMemoryGB} GB RAM required`:'Download'}</button>}</div></li>
 })}</ul>{error&&<p className="modal-error" role="alert">{error}</p>}</>
}
