import {useEffect,useRef,useState,type RefObject} from 'react'
import {useLocale} from '../i18n/Locale'
import {roomBase,roomRequest,type LiveKind,type LiveRoom} from './client'
import {useLiveMedia} from './useLiveMedia'
import './live.css'
function Video({stream,muted,label,avatar=false}:{stream?:MediaStream;muted:boolean;label:string;avatar?:boolean}){
 const ref=useRef<HTMLVideoElement>(null);const [blocked,setBlocked]=useState(false)
 useEffect(()=>{const v=ref.current;if(!v)return;let mounted=true;v.srcObject=stream??null;setBlocked(false);if(stream)void v.play().then(()=>{if(mounted)setBlocked(false)}).catch(()=>{if(mounted)setBlocked(true)});return()=>{mounted=false;v.srcObject=null}},[stream])
 return <><video style={avatar?{opacity:0}:undefined} ref={ref} autoPlay playsInline muted={muted}/>{(!stream||avatar)&&<span className="live-avatar">{label.slice(0,1).toUpperCase()}</span>}{blocked&&stream&&<button className="modal-btn" onClick={e=>{e.stopPropagation();void ref.current?.play().then(()=>setBlocked(false))}}>{'▶'}</button>}<span className="live-name">{label}</span></>
}
export function LiveChat({kind,invite,name,submitRef,onClose}:{kind:LiveKind;invite?:string;name:string;submitRef:RefObject<((text:string)=>void)|null>;onClose:()=>void}){
 const {t}=useLocale();const [step,setStep]=useState(invite?'join':kind==='syberlive'?'size':'motion'),[motion,setMotion]=useState(''),[room,setRoom]=useState<LiveRoom|null>(null),[local,setLocal]=useState<MediaStream|null>(null),[error,setError]=useState(''),[notes,setNotes]=useState<string[]>([]),[busy,setBusy]=useState(false),[link,setLink]=useState(''),[displayName,setDisplayName]=useState(name),[password,setPassword]=useState(''),[side,setSide]=useState<'for'|'against'>('for'),[featured,setFeatured]=useState(''),[clock,setClock]=useState(Date.now()),[draft,setDraft]=useState('')
 const token=useRef(''),session=useRef<LiveRoom|null>(null),tracks=useRef<MediaStream[]>([]),alive=useRef(true),pending=useRef(false),offset=useRef(0)
 const media=useLiveMedia(room,token.current,local,setError)
 const title=kind==='syberlive'?'SyberLive 1.0':'Crossfire 1.0'
 const cleanup=()=>{for(const stream of tracks.current)for(const track of stream.getTracks())track.stop();tracks.current=[];setLocal(null);session.current=null;token.current='';setRoom(null);setLink('');setNotes([]);setStep('ended');history.replaceState(null,'',location.pathname+location.search)}
 const leave=()=>{const r=session.current;if(r){navigator.sendBeacon(`${roomBase}/api/rooms/leave`,new Blob([JSON.stringify({room:r.id,token:token.current})],{type:'application/json'}))}for(const stream of tracks.current)stream.getTracks().forEach(track=>track.stop())}
 useEffect(()=>{alive.current=true;window.addEventListener('pagehide',leave);return()=>{alive.current=false;leave();window.removeEventListener('pagehide',leave)}},[])
 useEffect(()=>{if(!room)return;const timer=setInterval(()=>setClock(Date.now()+offset.current),250);return()=>clearInterval(timer)},[!!room])
 useEffect(()=>{if(!room)return;let stopped=false,polling=false,failures=0;const poll=async()=>{if(stopped||polling)return;polling=true;try{const next=await roomRequest('poll',{room:room.id,token:token.current});if(!stopped&&session.current?.id===room.id){failures=0;offset.current=next.now-Date.now();setRoom(next);session.current=next}}catch(e){if(!stopped){setError(e instanceof Error?e.message:'Room request failed.');if(++failures>=3||String(e).includes('ended'))cleanup()}}finally{polling=false}};const timer=setInterval(()=>void poll(),1200);return()=>{stopped=true;clearInterval(timer)}},[room?.id])
 async function capture(host:boolean){
  if(!navigator.mediaDevices?.getUserMedia){if(kind==='syberlive')throw Error('Camera unavailable. Open this link on a phone or computer.');setNotes(old=>[...old,t('Camera unavailable. Joining muted with an avatar.')]);return null}
  try{const stream=await navigator.mediaDevices.getUserMedia({video:kind==='crossfire'?{width:{ideal:160},height:{ideal:120},frameRate:{ideal:5,max:8}}:{width:{ideal:640},height:{ideal:360},frameRate:{ideal:20,max:24}},audio:true});if(!alive.current){stream.getTracks().forEach(track=>track.stop());throw Error('Room closed.')}if(kind==='crossfire')stream.getAudioTracks().forEach(track=>track.enabled=false);tracks.current.push(stream);setLocal(stream);return stream}
  catch{if(kind==='syberlive')throw Error('Camera and microphone permission is required. The room was not opened.');setNotes(old=>[...old,t(host?'Camera or microphone denied. You can host muted with an avatar.':'Camera or microphone denied. Joining muted with an avatar.')]);return null}
 }
 async function start(body:object,joining=false){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await roomRequest('health',{});await capture(!joining);const result=await roomRequest(joining?'join':'create',body);if(!alive.current){void roomRequest('leave',{room:result.id,token:result.token});return}token.current=result.token!;session.current=result;setRoom(result);setStep('room');setFeatured(result.members.find(m=>m.host)?.id??result.self);offset.current=result.now-Date.now();if(!joining){const url=new URL(location.href);url.hash=new URLSearchParams({live:kind,room:result.id}).toString();setLink(url.href)}}catch(e){tracks.current.forEach(s=>s.getTracks().forEach(t=>t.stop()));tracks.current=[];setLocal(null);setError(e instanceof Error?e.message:'Room request failed.')}finally{pending.current=false;setBusy(false)}}
 async function action(action:string,extra:object={}){if(!room)return;try{await roomRequest(action,{room:room.id,token:token.current,...extra});if(action==='end'||action==='leave')cleanup()}catch(e){setError(e instanceof Error?e.message:'Room request failed.')}}
 function exit(){const current=session.current;if(!current){onClose();return}void Promise.resolve(action(current.host?'end':'leave')).finally(onClose)}
 async function submit(text:string){if(pending.current||!text.trim())return;if(room){await action('message',{text});return}if(step==='size'){const limit=Number(text.trim());if(![2,3,4].includes(limit)){setError('Choose 2, 3 or 4 people.');return}await start({kind,limit,name});return}if(step==='motion'){if(text.trim().length>300){setError('Enter a motion of up to 300 characters.');return}setMotion(text.trim());setStep('password');setError('');return}if(step==='password'){await start({kind,motion,password:['open','ღია','открыто'].includes(text.trim().toLowerCase())?'':text,name});return}}
 useEffect(()=>{submitRef.current=text=>void submit(text);return()=>{submitRef.current=null}})
 const question=step==='size'?'How many people? Enter 2, 3 or 4.':step==='motion'?'What is the motion? Write one sentence.':step==='password'?'Choose a password, or type open for link-only access.':step==='ended'?'This room has ended or does not exist.':''
 const host=room?.members.find(m=>m.host),promoted=room?.members.find(m=>m.id===featured)??host,round=room?.round
 const speaker=round?.point?.id??round?.speaker
 function tile(member:NonNullable<LiveRoom>['members'][number],large=false){const guests=room?.members.filter(m=>!m.host)??[];const angle=2*Math.PI*guests.findIndex(m=>m.id===member.id)/Math.max(1,guests.length)-Math.PI/2;const position=kind==='crossfire'&&!member.host?{['--tile-x' as string]:`${50+(guests.length>1?28*Math.cos(angle):0)}%`,['--tile-y' as string]:`${50+(guests.length>1?28*Math.sin(angle):0)}%`}:undefined;return <div className={`live-tile${large?' live-large':''}`} key={member.id} style={position}><div role="button" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')setFeatured(member.id)}} className="live-promote" aria-label={t('Promote video')} onClick={()=>setFeatured(member.id===promoted?.id?host?.id??member.id:member.id)}><Video avatar={media.pausedVideo[member.id]} label={`${member.name}${member.host?` · ${t('Host')}`:''}`} stream={member.id===room?.self?media.sharedStream??local??undefined:media.streams[member.id]} muted={member.id===room?.self||(kind==='crossfire'&&member.id!==speaker)}/></div>{member.side&&<span className="live-side">{t(member.side==='for'?'For':'Against')}</span>}</div>}
 return <div data-step={step} className={`live-page live-page-${kind} live-chat`} role="dialog" aria-modal="true" aria-label={title}>
 <button type="button" className="live-page-close" onClick={exit}>{t('Close')}</button>
 <div className="live-page-body">
 <div className="msg-bubble msg-assistant">{title}{question&&<p>{t(question)}</p>}</div>{step==='join'&&<form className="live-join" onSubmit={e=>{e.preventDefault();void start({room:invite,name:displayName,password,side},true)}}><label>{t('Your name')}<input required maxLength={48} value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label>{kind==='crossfire'&&<><label>{t('Room password')}<input type="password" value={password} maxLength={128} onChange={e=>setPassword(e.target.value)}/></label><div>{(['for','against'] as const).map(v=><button type="button" className="modal-btn" aria-pressed={side===v} key={v} onClick={()=>setSide(v)}>{t(v==='for'?'For':'Against')}</button>)}</div></>}<button className="modal-btn" disabled={busy}>{t('Join room')}</button></form>}{busy&&<p role="status">{t('Preparing room…')}</p>}{notes.map((note,i)=><p key={i}>{note}</p>)}{error&&<p className="modal-error" role="alert">{t(error)}</p>}{room&&<>
  <section data-version="1.0.0" className={`live-stage ${kind} members-${room.members.length}`} aria-label={title}><header><strong>{title}</strong><span>{room.members.length}/{room.limit}</span><button className="modal-btn" onClick={()=>void action(room.host?'end':'leave')}>{t(room.host?'End room':'Leave room')}</button></header>{kind==='crossfire'&&<h3>{room.motion}</h3>}{kind==='syberlive'?<div className="live-video-layout live-player-frame">{room.members.length<=2?room.members.map(m=>tile(m,true)):<>{promoted&&tile(promoted,true)}<div className="live-small-row">{room.members.filter(m=>m.id!==promoted?.id).map(m=>tile(m))}</div></>}</div>:<><div className="crossfire-fit"><div className="crossfire-host">{host&&tile(host)}</div><div className="crossfire-stage"><div className="crossfire-circle">{room.members.filter(m=>!m.host).map(m=>tile(m))}</div></div></div><div className="crossfire-floor" role="status">{round?`${t(round.side==='for'?'For':'Against')} · ${room.members.find(m=>m.id===speaker)?.name??''} · ${Math.max(0,Math.ceil((round.end-clock)/1000))}s`:t('Waiting for the host to ask.')}{round&&(clock-round.start<10000||round.end-clock<=10000)&&<span> · {t('Protected time')}</span>}</div><div className="live-controls">{room.host&&<><button className="modal-btn" disabled={!!round} onClick={()=>void action('ask')}>{t('Ask')}</button><button className="modal-btn" disabled={!round} onClick={()=>void action('cut')}>{t('Cut mic')}</button><button className="modal-btn" disabled={!round} onClick={()=>void action('skip')}>{t('Skip side')}</button><button className="modal-btn" disabled={!round} onClick={()=>void action('stop-round')}>{t('End round')}</button><button className="modal-btn" onClick={()=>void media.shareScreen().then(stream=>{if(stream)tracks.current.push(stream)}).catch(()=>setError('Screen sharing permission was denied.'))}>{t(media.sharedStream?'Stop sharing':'Share screen')}</button></>}{!room.host&&<button className="modal-btn" disabled={!round||room.self===speaker||clock-round.start<10000||round.end-clock<=10000||!!round.point} onClick={()=>void action('point')}>{t('Request a Point')}</button>}{round&&(room.host||room.self===round.speaker)&&round.requests.map(id=><button className="modal-btn" key={id} onClick={()=>void action('allow-point',{member:id})}>{t('Allow Point')} · {room.members.find(m=>m.id===id)?.name}</button>)}</div></>}
  <footer>{t(kind==='syberlive'?'Private. Not recorded. Deleted when the room ends.':'Private debate. Not recorded. Deleted when the room ends.')}</footer></section>{link&&<div className="msg-bubble msg-assistant"><p>{t('Share this private link. It expires when the room ends.')}</p><button className="modal-btn" onClick={()=>void navigator.clipboard.writeText(link).catch(()=>setError('Copy failed. Select the link manually.'))}>{t('Copy invite link')}</button><input readOnly aria-label={t('Invite link')} value={link}/></div>}<div className="live-page-log">{room.messages.map(m=><div className="msg-bubble msg-assistant" key={m.id}><strong>{m.name}</strong><p>{m.text}</p></div>)}</div></>}
 {step==='ended'&&<button className="modal-btn" onClick={onClose}>{t('Home')}</button>}
 </div>
 {step!=='join'&&step!=='ended'&&<form className="live-page-composer" onSubmit={e=>{e.preventDefault();const text=draft.trim();if(!text||busy)return;setDraft('');void submit(text)}}><input aria-label={t(room?'Message':question||'Message')} placeholder={t(room?'Message':question||'Message')} value={draft} maxLength={room?500:step==='motion'?300:128} onChange={e=>setDraft(e.target.value)} disabled={busy} autoFocus /><button className="modal-btn" type="submit" disabled={busy||!draft.trim()}>{t('Send')}</button></form>}
 </div>
}
