import { useEffect, useRef, useState, type RefObject } from 'react'
import { useLocale } from '../i18n/Locale'
import { kasRequest } from './client'
import './kas.css'
export function Kas({onClose}:{onClose:()=>void}) {
 const {t}=useLocale();const [step,setStep]=useState(0),[text,setText]=useState(''),[questions,setQuestions]=useState(['','']),[answers,setAnswers]=useState(['','']),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false)
 const abort=useRef<AbortController|null>(null);useEffect(()=>()=>abort.current?.abort(),[])
 async function generate(){if(busy)return;setBusy(true);setError('');const controller=new AbortController();abort.current=controller;try{const result=await kasRequest({action:'create',text,questions,answers},controller.signal);setCode(result.code!);setText('');setAnswers(['','']);setQuestions(['','']);setStep(2)}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'KAS request failed.')}finally{setBusy(false)}}
 return <div className="watch-backdrop kas-backdrop"><section className="watch-panel kas-panel" role="dialog" aria-modal="true" aria-label="KAS 1.0"><header className="watch-header"><div><h2>KAS 1.0</h2><span>Keeping a secret</span></div><button className="modal-btn" onClick={onClose}>{t('Close')}</button></header><p className="modal-help">{t('Unopened secrets expire after 30 days. After unlocking, choose deletion or public access for the remaining 10-minute window.')}</p>
 {step===0?<form onSubmit={e=>{e.preventDefault();setStep(1)}}><label>{t('Your secret')}<textarea required maxLength={20000} value={text} onChange={e=>setText(e.target.value)} /></label><button className="modal-btn primary" disabled={!text.trim()}>{t('Next')}</button></form>:step===1?<form onSubmit={e=>{e.preventDefault();void generate()}}>{questions.map((q,i)=><fieldset key={i}><legend>{t('Question')} {i+1}/{questions.length}</legend><input disabled={busy} required maxLength={300} value={q} aria-label={`${t('Question')} ${i+1}`} onChange={e=>setQuestions(previous=>previous.map((v,n)=>n===i?e.target.value:v))}/><input disabled={busy} required type="password" autoComplete="off" maxLength={300} value={answers[i]} aria-label={`${t('Answer')} ${i+1}`} placeholder={t('Answer')} onChange={e=>setAnswers(previous=>previous.map((v,n)=>n===i?e.target.value:v))}/></fieldset>)}<div className="kas-pair-controls"><button type="button" className="modal-btn" aria-label={t('Remove last question and answer')} title={t('Remove last question and answer')} disabled={busy||questions.length<=1} onClick={()=>{setQuestions(v=>v.slice(0,-1));setAnswers(v=>v.slice(0,-1))}}>−</button><span aria-live="polite">{questions.length} / 6 · {t('Questions')}</span><button type="button" className="modal-btn" aria-label={t('Add question and answer')} title={t('Add question and answer')} disabled={busy||questions.length>=6} onClick={()=>{setQuestions(v=>[...v,'']);setAnswers(v=>[...v,''])}}>+</button></div><p className="modal-help">{t('Answers are case-sensitive. Choose answers that others cannot easily guess.')}</p><button type="button" className="modal-btn" disabled={busy} onClick={()=>setStep(0)}>{t('Back')}</button><button className="modal-btn primary" disabled={busy||[...questions,...answers].some(v=>!v.trim())}>{t(busy?'Saving…':'Generate')}</button></form>:<div><p className="kas-success">{t('Successfully saved in my brain.')}</p><code className="kas-code">{code}</code><button className="modal-btn" onClick={()=>{void navigator.clipboard.writeText(code).then(()=>setCopied(true)).catch(()=>setError('Copy failed. Select the code and copy it manually.'))}}>{t(copied?'Copied':'Copy')}</button><p>{t('Paste this code into the chat. All answers are required to unlock it. Public access is optional after unlocking.')}</p></div>}{error&&<p role="alert" className="modal-error">{t(error)}</p>}</section></div>
}
// Reveal text in short bursts, with brief pauses at punctuation.
function KasTypedText({text,onComplete,slow=false}:{text:string;onComplete?:()=>void;slow?:boolean}) {
 const complete=useRef(onComplete);complete.current=onComplete
 const [visible,setVisible]=useState('')
 useEffect(()=>{
  const media=window.matchMedia('(prefers-reduced-motion: reduce)')
  let timer:ReturnType<typeof setTimeout>|undefined,position=0,done=false
  const notify=()=>{if(!done){done=true;complete.current?.()}}
  const characters=Array.from(text)
  const finish=()=>{clearTimeout(timer);setVisible(text);notify()}
  const tick=()=>{
   const count=Math.max(1,Math.ceil(characters.length/320))
   position=Math.min(characters.length,position+(slow?1:count+(position%3===0?1:0)))
   setVisible(characters.slice(0,position).join(''))
   if(position<characters.length){const last=characters[position-1];timer=setTimeout(tick,/[.!?\n]/.test(last)?210:/[,;:]/.test(last)?110:(slow?105:32)+(position%4)*10)}else notify()
  }
  setVisible('')
  if(media.matches)finish();else timer=setTimeout(tick,160)
  const changed=()=>{if(media.matches)finish()}
  media.addEventListener('change',changed)
  return()=>{clearTimeout(timer);media.removeEventListener('change',changed)}
 },[text,slow])
 return <><span className="sr-only">{text}</span><span aria-hidden="true">{visible}{visible!==text&&<span className="kas-typing-caret">▍</span>}</span></>
}
export function KasReader({code,onClose,submitRef}:{code:string;onClose:()=>void;submitRef:RefObject<((text:string)=>void)|null>}){
 const {t}=useLocale();const [stage,setStage]=useState('loading'),[verified,setVerified]=useState<string[]>([]),[count,setCount]=useState(2),[proof,setProof]=useState(''),[secret,setSecret]=useState(''),[token,setToken]=useState(''),[authorId,setAuthorId]=useState(''),[deadline,setDeadline]=useState(0),[remaining,setRemaining]=useState(0),[busy,setBusy]=useState(false),[published,setPublished]=useState(false),[introIndex,setIntroIndex]=useState(0)
 const [lines,setLines]=useState<{text:string;user?:boolean;tone?:string;intro?:number;localized?:boolean}[]>([
  'You are in the KAS secret space. Answer each question exactly as the author did.',
  'After unlocking, choose permanent deletion or public access with the code for the remaining 10 minutes.',
 ].map((text,intro)=>({text,intro,localized:true})));const abort=useRef(new AbortController()),lane=useRef<HTMLDivElement>(null),pending=useRef(false)
 const say=(text:string,tone?:string)=>setLines(old=>[...old,{text,tone,localized:true}])
 useEffect(()=>{const c=new AbortController();abort.current=c;void kasRequest({action:'questions',code},c.signal).then(r=>{if(r.text!==undefined){reveal(r);setPublished(true);setLines([{text:'This secret is public to anyone with its code until the timer ends.',localized:true}])}else {setCount(r.count??2);setLines(old=>[...old,{text:r.questions![0],tone:'question',intro:2}]);setStage('answer')}}).catch(e=>{if(!c.signal.aborted){say(e.message,'wrong');setStage('done')}});return()=>c.abort()},[code])
 function reveal(r:Awaited<ReturnType<typeof kasRequest>>){setSecret(r.text!);setAuthorId(r.authorId??'');setToken(r.deleteToken!);setDeadline(Date.now()+r.remainingMs!);setRemaining(r.remainingMs!);setStage('revealed');setVerified([]);setProof('')}
 useEffect(()=>{const element=lane.current;if(!element)return;let following=true;const scroll=()=>{following=element.scrollHeight-element.scrollTop-element.clientHeight<90};const observer=new MutationObserver(()=>{if(following)element.scrollTop=element.scrollHeight});element.addEventListener('scroll',scroll,{passive:true});observer.observe(element,{subtree:true,childList:true,characterData:true});return()=>{observer.disconnect();element.removeEventListener('scroll',scroll)}},[])
 useEffect(()=>{lane.current?.scrollTo({top:lane.current.scrollHeight,behavior:'smooth'})},[lines,secret,introIndex])
 useEffect(()=>{if(!deadline)return;const update=()=>{const left=Math.max(0,deadline-Date.now());setRemaining(left);if(!left){setSecret('');setToken('');setStage('done')}};update();const timer=setInterval(update,500);window.addEventListener('focus',update);return()=>{clearInterval(timer);window.removeEventListener('focus',update)}},[deadline])
 async function submit(answer:string){if(pending.current||!answer.trim())return
  if(stage!=='answer'){say('Use the actions below the original text, or close the chat.');return}
  pending.current=true;setBusy(true);setLines(old=>[...old,{text:'••••••',user:true}]);try{if(verified.length<count-1){const r=await kasRequest({action:'verify',code,answer,index:verified.length,proof},abort.current.signal);setVerified(v=>[...v,answer]);setProof(r.proof!);say('Correct answer.','correct');setLines(old=>[...old,{text:r.question!,tone:'question'}]);setStage('answer')}else{const r=await kasRequest({action:'unlock',code,answers:[...verified,answer],proof},abort.current.signal);say('Correct answer.','correct');reveal(r)}}catch(e){if(!abort.current.signal.aborted)say(e instanceof Error&&e.message==='The answers are incorrect.'?'Sorry, the answer does not match. Enter exactly what the author wrote, including capitalization and spaces.':e instanceof Error?e.message:'KAS request failed.','wrong')}finally{pending.current=false;setBusy(false)}}
 useEffect(()=>{submitRef.current=text=>{void submit(text)};return()=>{submitRef.current=null}})
 async function action(kind:'delete'|'publish'){if(pending.current)return;pending.current=true;setBusy(true);try{await kasRequest({action:kind,code,deleteToken:token},abort.current.signal);if(kind==='delete'){setSecret('');setToken('');setStage('deleted');setDeadline(0);say('The secret has been permanently deleted.','correct')}else{setPublished(true);say('This secret is public to anyone with its code until the timer ends.','correct')}}catch(e){say(e instanceof Error?e.message:'KAS request failed.','wrong')}finally{pending.current=false;setBusy(false)}}
 const seconds=Math.ceil(remaining/1000)
 return <div className="history-lane kas-chat" ref={lane} aria-live="polite">{lines.map((line,i)=>line.intro!==undefined&&line.intro>introIndex?null:<div key={i} className={`msg-bubble ${line.user?'msg-user':'msg-assistant'} kas-line-${line.tone||'normal'}`}>{line.user?line.text:<KasTypedText text={line.localized?t(line.text):line.text} slow={line.tone==='question'} onComplete={line.intro===undefined?undefined:()=>setIntroIndex(current=>Math.max(current,Math.min(3,line.intro!+1)))}/>}</div>)}{busy&&<div className="msg-bubble msg-assistant">{t('Checking…')}</div>}{secret&&<div className="msg-bubble msg-assistant kas-original"><small className="kas-author">{t('Anonymous author ID')}: {authorId}</small><pre><KasTypedText text={secret}/></pre><p>{t('Time remaining')}: {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</p><div className="kas-inline-actions"><button className="modal-btn kas-action-delete" disabled={busy} onClick={()=>void action('delete')}>{t('DELETE')}</button><button className="modal-btn kas-action-public" disabled={busy||published} onClick={()=>void action('publish')}>{t(published?'Public until timer ends':'Publish (10 min)')}</button></div></div>}{stage==='done'&&!secret&&<div className="msg-bubble msg-assistant">{t('This secret has expired or does not exist.')}<button className="modal-btn" onClick={onClose}>{t('Home')}</button></div>}</div>
}
