import { createPortal } from 'react-dom'
import { useEffect, useRef, useState } from 'react'
import { useLocale } from '../i18n/Locale'
import { kasRequest } from './client'
import './kas.css'
export function Kas({onClose}:{onClose:()=>void}) {
 const {t}=useLocale();const [step,setStep]=useState(0),[text,setText]=useState(''),[questions,setQuestions]=useState(['','']),[answers,setAnswers]=useState(['','']),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false)
 const abort=useRef<AbortController|null>(null);useEffect(()=>()=>abort.current?.abort(),[])
 async function generate(){if(busy)return;setBusy(true);setError('');const controller=new AbortController();abort.current=controller;try{const result=await kasRequest({action:'create',text,questions,answers},controller.signal);setCode(result.code!);setText('');setAnswers(['','']);setQuestions(['','']);setStep(2)}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'KAS request failed.')}finally{setBusy(false)}}
 return <div className="watch-backdrop kas-backdrop"><section className="watch-panel kas-panel" role="dialog" aria-modal="true" aria-label="KAS 1.0"><header className="watch-header"><div><h2>KAS 1.0</h2><span>Keeping a secret</span></div><button className="modal-btn" onClick={onClose}>{t('Close')}</button></header><p className="modal-help">{t('Unopened secrets expire after 30 days. After the first successful unlock, anyone with the code can read the text for 10 minutes. The timer cannot be extended.')}</p>
 {step===0?<form onSubmit={e=>{e.preventDefault();setStep(1)}}><label>{t('Your secret')}<textarea required maxLength={20000} value={text} onChange={e=>setText(e.target.value)} /></label><button className="modal-btn primary" disabled={!text.trim()}>{t('Next')}</button></form>:step===1?<form onSubmit={e=>{e.preventDefault();void generate()}}>{questions.map((q,i)=><fieldset key={i}><legend>{t('Question')} {i+1}/2</legend><input required maxLength={300} value={q} aria-label={`${t('Question')} ${i+1}`} onChange={e=>setQuestions(previous=>previous.map((v,n)=>n===i?e.target.value:v))}/><input required type="password" autoComplete="off" maxLength={300} value={answers[i]} aria-label={`${t('Answer')} ${i+1}`} placeholder={t('Answer')} onChange={e=>setAnswers(previous=>previous.map((v,n)=>n===i?e.target.value:v))}/></fieldset>)}<p className="modal-help">{t('Answers are case-sensitive. Choose answers that others cannot easily guess.')}</p><button type="button" className="modal-btn" disabled={busy} onClick={()=>setStep(0)}>{t('Back')}</button><button className="modal-btn primary" disabled={busy||[...questions,...answers].some(v=>!v.trim())}>{t(busy?'Saving…':'Generate')}</button></form>:<div><p className="kas-success">{t('Successfully saved in my brain.')}</p><code className="kas-code">{code}</code><button className="modal-btn" onClick={()=>{void navigator.clipboard.writeText(code).then(()=>setCopied(true)).catch(()=>setError('Copy failed. Select the code and copy it manually.'))}}>{t(copied?'Copied':'Copy')}</button><p>{t('Paste this code into the chat. Both answers are required for the first unlock. Afterwards, the code reveals the text for the remaining 10-minute window.')}</p></div>}{error&&<p role="alert" className="modal-error">{t(error)}</p>}</section></div>
}
export function KasReader({code,onClose}:{code:string;onClose:()=>void}){
 const {t}=useLocale()
 const [question,setQuestion]=useState(''),[typed,setTyped]=useState(''),[first,setFirst]=useState(''),[proof,setProof]=useState(''),[answer,setAnswer]=useState(''),[secret,setSecret]=useState(''),[deleteToken,setDeleteToken]=useState(''),[deadline,setDeadline]=useState(0),[remaining,setRemaining]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[feedback,setFeedback]=useState(''),[confirm,setConfirm]=useState(false)
 const abort=useRef<AbortController|null>(null)
 useEffect(()=>{const c=new AbortController();abort.current=c;void kasRequest({action:'questions',code},c.signal).then(r=>{if(r.text!==undefined){setSecret(r.text);setDeleteToken(r.deleteToken!);setDeadline(Date.now()+r.remainingMs!);setRemaining(r.remainingMs!)}else setQuestion(r.questions![0])}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[code])
 useEffect(()=>{setTyped('');if(!question)return;if(matchMedia('(prefers-reduced-motion: reduce)').matches){setTyped(question);return}let n=0;const timer=setInterval(()=>{n++;setTyped(question.slice(0,n));if(n>=question.length)clearInterval(timer)},24);return()=>clearInterval(timer)},[question])
 useEffect(()=>{if(!deadline)return;const update=()=>{const left=Math.max(0,deadline-Date.now());setRemaining(left);if(!left){setSecret('');setDeleteToken('');setFirst('');setQuestion('');setError('This secret has expired or does not exist.')}};update();const timer=setInterval(update,250);window.addEventListener('focus',update);return()=>{clearInterval(timer);window.removeEventListener('focus',update)}},[deadline])
 useEffect(()=>{if(!secret)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();setConfirm(true)}};document.addEventListener('keydown',onKey,true);return()=>document.removeEventListener('keydown',onKey,true)},[secret])
 async function submit(){if(busy||!answer.trim())return;setBusy(true);setError('');setFeedback('checking');try{
  if(!proof){const r=await kasRequest({action:'verify',code,answer},abort.current?.signal);setFeedback('correct');await new Promise(resolve=>setTimeout(resolve,650));if(abort.current?.signal.aborted)return;setFirst(answer);setAnswer('');setProof(r.proof!);setQuestion(r.question!)}
  else{const r=await kasRequest({action:'unlock',code,answers:[first,answer],proof},abort.current?.signal);setFeedback('correct');setFirst('');setAnswer('');setQuestion('');setDeleteToken(r.deleteToken!);setSecret(r.text!);setDeadline(Date.now()+r.remainingMs!);setRemaining(r.remainingMs!)}
 }catch(e){if(abort.current?.signal.aborted)return;const message=e instanceof Error?e.message:'KAS request failed.';setFeedback(message==='The answers are incorrect.'?'wrong':'');setError(message==='The answers are incorrect.'?'Sorry, the answer does not match. Enter exactly what the author wrote, including capitalization and spaces.':message)}finally{setBusy(false)}}
 async function remove(){if(busy)return;setBusy(true);setError('');try{await kasRequest({action:'delete',code,deleteToken},abort.current?.signal);setSecret('');setDeleteToken('');onClose()}catch(e){if(e instanceof Error&&e.message==='This secret has expired or does not exist.'){setSecret('');onClose();return}setError(e instanceof Error?e.message:'KAS request failed.')}finally{setBusy(false)}}
 const seconds=Math.ceil(remaining/1000),clock=[Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60].map(n=>String(n).padStart(2,'0')).join(':')
 if(secret)return createPortal(<div className="kas-reveal" role="dialog" aria-modal="true" aria-label={t('Original Text')}><header><div><small>KAS 1.0 · robaqAI</small><h2>{t('Original Text')}</h2></div><button autoFocus className="kas-x" aria-label={t('Close')} onClick={()=>setConfirm(true)}>×</button></header><div className="kas-countdown"><span>{t('Time remaining')}</span><strong>{clock}</strong></div><pre>{secret}</pre><button className="modal-btn" onClick={()=>void navigator.clipboard.writeText(secret).catch(()=>setError('Copy failed. Select the text and copy it manually.'))}>{t('Copy')}</button>{error&&<p role="alert">{t(error)}</p>}{confirm&&<div className="kas-confirm"><section role="alertdialog" aria-modal="true" aria-labelledby="kas-delete-title"><h2 id="kas-delete-title">{t('Delete this secret?')}</h2><p>{t('Take a screenshot or copy the text first. Closing now permanently deletes the secret for everyone. This cannot be undone.')}</p><button autoFocus className="modal-btn" disabled={busy} onClick={()=>setConfirm(false)}>{t('Back')}</button><button className="modal-btn kas-delete" disabled={busy} onClick={()=>void remove()}>{t(busy?'Deleting…':'Delete and close')}</button>{error&&<p role="alert">{t(error)}</p>}</section></div>}</div>,document.body)
 return <section className={`kas-reader kas-${feedback}`} aria-label="KAS 1.0"><header><span>KAS 1.0 · Keeping a secret</span><button className="kas-x" aria-label={t('Close')} onClick={onClose}>×</button></header><div className="kas-question-area"><div className="kas-orb" aria-hidden>✦</div><small>robaqAI · {t('Question')} {proof?'2':'1'}/2</small><h2 aria-label={question}><span aria-hidden>{typed}</span><span className="kas-caret" aria-hidden>▏</span></h2><p className="kas-detector" role="status">{t(feedback==='checking'?'Checking your answer…':feedback==='correct'?'Correct answer.':feedback==='wrong'?'Answer does not match.':'Two answers. One secret.')}</p><small>{t('The detector checks answer matching, not truthfulness.')}</small>{error&&<p className="kas-error" role="alert">{t(error)}</p>}</div>{question&&<form onSubmit={e=>{e.preventDefault();void submit()}}><input autoFocus required type="password" autoComplete="off" maxLength={300} value={answer} aria-label={t('Answer')} placeholder={t('Answer')} disabled={busy} onChange={e=>{setAnswer(e.target.value);setFeedback('');setError('')}}/><button className="modal-btn" disabled={busy||!answer.trim()}>{t(busy?'Checking…':'Verify')}</button></form>}</section>
}
