import { useEffect, useRef, useState } from 'react'
import { useLocale } from '../i18n/Locale'
import { kasRequest } from './client'
import './kas.css'
export function Kas({onClose}:{onClose:()=>void}) {
 const {t}=useLocale();const [step,setStep]=useState(0),[text,setText]=useState(''),[questions,setQuestions]=useState(['','']),[answers,setAnswers]=useState(['','']),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false)
 const abort=useRef<AbortController|null>(null);useEffect(()=>()=>abort.current?.abort(),[])
 async function generate(){if(busy)return;setBusy(true);setError('');const controller=new AbortController();abort.current=controller;try{const result=await kasRequest({action:'create',text,questions,answers},controller.signal);setCode(result.code!);setText('');setAnswers(['','']);setQuestions(['','']);setStep(2)}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'KAS request failed.')}finally{setBusy(false)}}
 return <div className="watch-backdrop kas-backdrop"><section className="watch-panel kas-panel" role="dialog" aria-modal="true" aria-label="KAS 1.0"><header className="watch-header"><div><h2>KAS 1.0</h2><span>Keeping a secret</span></div><button className="modal-btn" onClick={onClose}>{t('Close')}</button></header><p className="modal-help">{t('Unopened secrets expire after 30 days. The first successful unlock starts a one-hour timer that cannot be extended.')}</p>
 {step===0?<form onSubmit={e=>{e.preventDefault();setStep(1)}}><label>{t('Your secret')}<textarea required maxLength={20000} value={text} onChange={e=>setText(e.target.value)} /></label><button className="modal-btn primary" disabled={!text.trim()}>{t('Next')}</button></form>:step===1?<form onSubmit={e=>{e.preventDefault();void generate()}}>{questions.map((q,i)=><fieldset key={i}><legend>{t('Question')} {i+1}/2</legend><input required maxLength={300} value={q} aria-label={`${t('Question')} ${i+1}`} onChange={e=>setQuestions(previous=>previous.map((v,n)=>n===i?e.target.value:v))}/><input required type="password" autoComplete="off" maxLength={300} value={answers[i]} aria-label={`${t('Answer')} ${i+1}`} placeholder={t('Answer')} onChange={e=>setAnswers(previous=>previous.map((v,n)=>n===i?e.target.value:v))}/></fieldset>)}<p className="modal-help">{t('Answers are case-sensitive. Choose answers that others cannot easily guess.')}</p><button type="button" className="modal-btn" disabled={busy} onClick={()=>setStep(0)}>{t('Back')}</button><button className="modal-btn primary" disabled={busy||[...questions,...answers].some(v=>!v.trim())}>{t(busy?'Saving…':'Generate')}</button></form>:<div><p className="kas-success">{t('Successfully saved in my brain.')}</p><code className="kas-code">{code}</code><button className="modal-btn" onClick={()=>{void navigator.clipboard.writeText(code).then(()=>setCopied(true)).catch(()=>setError('Copy failed. Select the code and copy it manually.'))}}>{t(copied?'Copied':'Copy')}</button><p>{t('Paste this code into the chat. Both answers are required to reveal the original text.')}</p></div>}{error&&<p role="alert" className="modal-error">{t(error)}</p>}</section></div>
}
export function KasReader({code,onClose}:{code:string;onClose:()=>void}){
 const {t}=useLocale();const [questions,setQuestions]=useState<string[]>([]),[answers,setAnswers]=useState<string[]>([]),[answer,setAnswer]=useState(''),[secret,setSecret]=useState(''),[deadline,setDeadline]=useState(0),[remaining,setRemaining]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');const abort=useRef<AbortController|null>(null)
 useEffect(()=>{const c=new AbortController();abort.current=c;void kasRequest({action:'questions',code},c.signal).then(r=>setQuestions(r.questions!)).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[code])
 useEffect(()=>{if(!deadline)return;const update=()=>{const left=Math.max(0,deadline-Date.now());setRemaining(left);if(!left){setSecret('');setError('This secret has expired or does not exist.')}};update();const timer=setInterval(update,500);window.addEventListener('focus',update);return()=>{clearInterval(timer);window.removeEventListener('focus',update)}},[deadline])
 async function submit(){if(busy||!answer.trim())return;const next=[...answers,answer];setAnswer('');if(next.length===1){setAnswers(next);return}setBusy(true);setError('');try{const r=await kasRequest({action:'unlock',code,answers:next},abort.current?.signal);setAnswers([]);setQuestions([]);setSecret(r.text!);setDeadline(Date.now()+r.remainingMs!)}catch(e){setAnswers([]);setError(e instanceof Error?e.message:'KAS request failed.')}finally{setBusy(false)}}
 return <section className="kas-reader" aria-label="KAS 1.0" aria-live="polite"><button className="modal-btn" onClick={onClose}>{t('Close')}</button>{secret?<><strong className="kas-success">Original Text</strong><pre className="kas-success">{secret}</pre><p>{t('Time remaining')}: {Math.ceil(remaining/60000)} {t('minutes')}</p><button className="modal-btn" onClick={()=>void navigator.clipboard.writeText(secret).catch(()=>setError('Copy failed. Select the text and copy it manually.'))}>{t('Copy')}</button></>:questions.length>0?<form onSubmit={e=>{e.preventDefault();void submit()}}><label>{questions[answers.length]}<input autoFocus required type="password" autoComplete="off" maxLength={300} value={answer} onChange={e=>setAnswer(e.target.value)}/></label><button className="modal-btn" disabled={busy}>{t(answers.length?'Verify':'Next')}</button></form>:null}{error&&<p role="alert">{t(error)}</p>}</section>
}
