import {useTeslaLocation,enableTeslaLocation,stopTeslaLocation} from './location'
import {useEffect,useRef,useState} from 'react'
import {useLocale} from '../i18n/Locale'
import {skillPreferences} from '../skillSession'
import {finishInstallation,InstallProgress} from '../components/InstallProgress'
import {SkillHelp} from '../components/SkillHelp'
import './tesla.css'
export const TESLA_KEY='robaq-link-your-tesla-active'
const NOTES_KEY='robaq-link-your-tesla-notes'
export function removeTesla(){stopTeslaLocation();skillPreferences.removeItem(TESLA_KEY);skillPreferences.removeItem(NOTES_KEY)}
export function TeslaMark(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="10"/><path d="M7 7h10M12 7v11"/></svg>}
export function TeslaStore({active,onChange,onOpen}:{active:boolean;onChange:(active:boolean)=>void;onOpen:()=>void}){
 const {t}=useLocale(),[controller,setController]=useState<AbortController|null>(null)
 useEffect(()=>()=>controller?.abort(),[controller])
 return <div className="side-panel-item" data-skill="link-your-tesla" data-version="1.0.0"><div className="side-panel-item-body"><span className="side-panel-item-name">LinkyourTesla 1.0</span><span className="side-panel-item-meta">{t('Tesla screen mode. Red core. Live browser signals.')}</span></div><div className="model-actions"><SkillHelp name="LinkyourTesla 1.0" steps={['Install, then open Tesla below AI Lab.','Live shows browser signals only. Press Enable location to request permission.','Preview is illustrative, not vehicle data. Notes stay on this device; guest notes disappear on exit.','Uninstall removes this skill and its local notes.']}/>{controller?<><InstallProgress label={t('Installing…')} finishing/><button className="modal-btn" onClick={()=>controller.abort()}>{t('Cancel')}</button></>:active?<><span className="translator-active-badge">{t('Active')}</span><button className="modal-btn danger" onClick={()=>onChange(false)}>{t('Delete')}</button></>:<button className="modal-btn primary" onClick={()=>{const c=new AbortController();setController(c);void finishInstallation(c.signal).then(()=>{if(!c.signal.aborted){onChange(true);onOpen()}}).catch(()=>{}).finally(()=>setController(null))}}>{t('Download')}</button>}</div></div>
}
type Notes={nickname:string;charge:string;note:string}
export function TeslaPanel({onClose}:{onClose:()=>void}){
 const {t,locale}=useLocale(),dialog=useRef<HTMLDialogElement>(null)
 const [clock,setClock]=useState(()=>new Date()),[online,setOnline]=useState(navigator.onLine),[size,setSize]=useState(()=>`${screen.width} × ${screen.height}`)
 const {coordinates:location,status:locationState,enabled:locationEnabled}=useTeslaLocation()
 const [storageError,setStorageError]=useState(false)
 const [notes,setNotes]=useState<Notes>(()=>{try{const n=JSON.parse(skillPreferences.getItem(NOTES_KEY)||'{}');return {nickname:typeof n.nickname==='string'?n.nickname:'',charge:typeof n.charge==='string'?n.charge:'',note:typeof n.note==='string'?n.note:''}}catch{return {nickname:'',charge:'',note:''}}})
 useEffect(()=>{dialog.current?.showModal();const timer=setInterval(()=>setClock(new Date()),1000);const update=()=>{setOnline(navigator.onLine);setSize(`${screen.width} × ${screen.height}`)};window.addEventListener('online',update);window.addEventListener('offline',update);window.addEventListener('resize',update);return()=>{clearInterval(timer);window.removeEventListener('online',update);window.removeEventListener('offline',update);window.removeEventListener('resize',update)}},[])
 const number=(n:number|null|undefined,digits=2)=>typeof n==='number'&&Number.isFinite(n)?n.toFixed(digits):t('Unavailable')
 const save=(key:keyof Notes,value:string)=>{const next={...notes,[key]:value};setNotes(next);try{skillPreferences.setItem(NOTES_KEY,JSON.stringify(next));setStorageError(false)}catch{setStorageError(true)}}
 return <dialog ref={dialog} className="tesla-panel" onCancel={onClose} onClose={onClose} aria-labelledby="tesla-title"><header><div><span className="tesla-panel-mark"><TeslaMark/></span><h2 id="tesla-title">LinkyourTesla 1.0</h2></div><button className="modal-btn" onClick={onClose}>{t('Close')}</button></header><div className="tesla-columns"><section className="tesla-live"><h3>{t('Live · browser signals')}</h3><p>{t('Browser signals only, not vehicle diagnostics.')}</p><dl><div><dt>{t('Browser network status')}</dt><dd>{t(online?'Online':'Offline')}</dd></div><div><dt>{t('Local time')}</dt><dd>{clock.toLocaleTimeString(locale)}</dd></div><div><dt>{t('Timezone')}</dt><dd>{Intl.DateTimeFormat().resolvedOptions().timeZone||t('Unavailable')}</dd></div><div><dt>{t('Screen size')}</dt><dd>{size}</dd></div><div><dt>{t('Browser language')}</dt><dd>{navigator.language||t('Unavailable')}</dd></div></dl><button className="modal-btn" onClick={locationEnabled?stopTeslaLocation:enableTeslaLocation}>{t(locationEnabled?'Stop location':'Enable location')}</button><p role="status">{t(locationState)}</p><p>{t("Location stays on when you close this panel. While moving, browser GPS speed appears in the home core. Stop location turns it off.")}</p>{location&&<dl><div><dt>{t('Latitude')}</dt><dd>{number(location.latitude,5)}</dd></div><div><dt>{t('Longitude')}</dt><dd>{number(location.longitude,5)}</dd></div><div><dt>{t('Accuracy (m)')}</dt><dd>{number(location.accuracy)}</dd></div><div><dt>{t('Speed (m/s)')}</dt><dd>{number(location.speed)}</dd></div><div><dt>{t('Heading (°)')}</dt><dd>{number(location.heading)}</dd></div></dl>}</section><section className="tesla-preview"><h3>{t('Preview · not vehicle data')}</h3><p>{t('Illustrative placeholders. No connection to your vehicle.')}</p><div className="tesla-gauges"><div className="tesla-battery"><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="43"/></svg><span>— %</span></div><strong>{t('Battery preview')}</strong><div className="tesla-tires">{['Front left','Front right','Rear left','Rear right'].map(label=><div key={label}><span>{t(label)}</span><strong>—</strong></div>)}</div><p>{t('Cabin temperature')} · — °C</p></div></section></div><section className="tesla-notes"><h3>{t('Local notes')}</h3><p>{t('Notes stay on this device; guest notes disappear on exit.')}</p><div>{(['nickname','charge','note'] as const).map((key,i)=><label key={key}>{t(['Nickname','Last charge note','Free note'][i])}<textarea rows={key==='note'?3:1} maxLength={key==='note'?2000:200} value={notes[key]} onChange={e=>save(key,e.target.value)}/></label>)}</div>{storageError&&<p role="alert">{t('Local storage unavailable. Notes will not survive closing this panel.')}</p>}</section><footer>{t('Not affiliated with Tesla. For display only.')}</footer></dialog>
}
