import {useTeslaLocation,enableTeslaLocation,stopTeslaLocation} from './location'
import {useEffect,useRef,useState} from 'react'
import {useLocale} from '../i18n/Locale'
import {skillPreferences} from '../skillSession'
import {finishInstallation} from '../components/InstallProgress'
import {SkillHelp} from '../components/SkillHelp'
import './tesla.css'
export const TESLA_KEY='robaq-link-your-tesla-active'
export const TESLA_UNIT_KEY="robaq-tesla-unit"
const NOTES_KEY='robaq-link-your-tesla-notes'
export function removeTesla(){stopTeslaLocation();skillPreferences.removeItem(TESLA_KEY);skillPreferences.removeItem(NOTES_KEY);skillPreferences.removeItem(TESLA_UNIT_KEY)}
export function TeslaMark(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="10"/><path d="M7 7h10M12 7v11"/></svg>}
export function TeslaStore({active,onChange,onOpen}:{active:boolean;onChange:(active:boolean)=>void;onOpen:()=>void}){
 const location=useTeslaLocation()
 const {t}=useLocale(),[controller,setController]=useState<AbortController|null>(null),[connected,setConnected]=useState(false)
 useEffect(()=>()=>controller?.abort(),[controller])
 async function connect(){const c=new AbortController();let installed=false;const cancelLocation=()=>{if(!installed)stopTeslaLocation()};c.signal.addEventListener('abort',cancelLocation,{once:true});setController(c);setConnected(false);enableTeslaLocation();try{await finishInstallation(c.signal);if(c.signal.aborted)return;installed=true;onChange(true);setConnected(true);await new Promise<void>((resolve,reject)=>{const cancel=()=>{clearTimeout(timer);reject(new Error('cancelled'))};const timer=setTimeout(()=>{c.signal.removeEventListener('abort',cancel);resolve()},2000);c.signal.addEventListener('abort',cancel,{once:true})});if(!c.signal.aborted)onOpen()}catch{/* Cancel or unmount. */}finally{c.signal.removeEventListener('abort',cancelLocation);setController(null);setConnected(false)}}
 return <div className="side-panel-item" data-skill="link-your-tesla" data-version="1.0.0"><div className="side-panel-item-body"><span className="side-panel-item-name">LinkyourTesla 1.0</span><span className="side-panel-item-meta">{t('Tesla screen mode. Red core. Live browser signals.')}</span><small className="tesla-browser-note">{t('Open only in the Tesla browser.')}</small><small className="tesla-browser-note">{t('Connect requests location access. Choose Allow in your browser to enable GPS speed.')}</small><small className="tesla-browser-note">{t('While connected, activating an API key requests microphone, camera, and other browser permissions.')}</small>{(controller||active)&&<small className="tesla-browser-note" role="status">{t(location.status)}</small>}</div><div className="model-actions"><SkillHelp name="LinkyourTesla 1.0" steps={['Connect, then open Tesla below AI Lab.','Enable location and choose km/h or mph in TESLA Settings.','Live data shows browser signals only, not vehicle diagnostics.']}/>{controller&&!connected?<><span className="tesla-connecting">{t('Connecting')}<span aria-hidden="true">...</span></span><button className="modal-btn" onClick={()=>controller.abort()}>{t('Cancel')}</button></>:active?<><span className="translator-active-badge">{t('Connected')}</span><button className="modal-btn danger" onClick={()=>{controller?.abort();onChange(false)}}>{t('Disconnect')}</button></>:<button className="modal-btn primary" onClick={()=>void connect()}>{t('Connect')}</button>}</div></div>
}
export function TeslaSettings({unit,onUnit}:{unit:'km/h'|'mph';onUnit:(unit:'km/h'|'mph')=>void}){const {t}=useLocale();const location=useTeslaLocation();return <fieldset className="tesla-settings"><legend>TESLA Settings</legend><button className="modal-btn" onClick={location.enabled?stopTeslaLocation:enableTeslaLocation}>{t(location.enabled?'Stop location':'Enable location')}</button><p className="modal-help" role="status">{t(location.status)}</p><p className="modal-help">{t('Browser location permission: {0}').replace('{0}',t(location.permission))}</p><label className="settings-language">{t('Speed unit')}<select value={unit} onChange={e=>onUnit(e.target.value as 'km/h'|'mph')}><option value="km/h">km/h</option><option value="mph">mph</option></select></label></fieldset>}
export function TeslaPanel({onClose,unit='mph'}:{onClose:()=>void;unit?:'km/h'|'mph'}){
 const {t,locale}=useLocale(),dialog=useRef<HTMLDialogElement>(null)
 const [clock,setClock]=useState(()=>new Date()),[online,setOnline]=useState(navigator.onLine),[size,setSize]=useState(()=>`${screen.width} × ${screen.height}`)
 const {coordinates:location,status:locationState,enabled:locationEnabled}=useTeslaLocation()
 useEffect(()=>{dialog.current?.showModal();const timer=setInterval(()=>setClock(new Date()),1000);const update=()=>{setOnline(navigator.onLine);setSize(`${screen.width} × ${screen.height}`)};window.addEventListener('online',update);window.addEventListener('offline',update);window.addEventListener('resize',update);return()=>{clearInterval(timer);window.removeEventListener('online',update);window.removeEventListener('offline',update);window.removeEventListener('resize',update)}},[])
 const number=(n:number|null|undefined,digits=2)=>typeof n==='number'&&Number.isFinite(n)?n.toFixed(digits):t('Unavailable')
 return <dialog ref={dialog} className="tesla-panel" onCancel={onClose} onClose={onClose} aria-labelledby="tesla-title"><header><div><span className="tesla-panel-mark"><TeslaMark/></span><h2 id="tesla-title">LinkyourTesla 1.0</h2></div><button className="modal-btn" onClick={onClose}>{t('Close')}</button></header><div className="tesla-columns tesla-live-only"><section className="tesla-live"><h3>{t('Live data')}</h3><p>{t('Browser signals only, not vehicle diagnostics.')}</p><dl><div><dt>{t('Browser network status')}</dt><dd>{t(online?'Online':'Offline')}</dd></div><div><dt>{t('Local time')}</dt><dd>{clock.toLocaleTimeString(locale)}</dd></div><div><dt>{t('Timezone')}</dt><dd>{Intl.DateTimeFormat().resolvedOptions().timeZone||t('Unavailable')}</dd></div><div><dt>{t('Screen size')}</dt><dd>{size}</dd></div><div><dt>{t('Browser language')}</dt><dd>{navigator.language||t('Unavailable')}</dd></div></dl><button className="modal-btn" onClick={locationEnabled?stopTeslaLocation:enableTeslaLocation}>{t(locationEnabled?'Stop location':'Enable location')}</button><p role="status">{t(locationState)}</p><p>{t("Location stays on when you close this panel. While moving, browser GPS speed appears in the home core. Stop location turns it off.")}</p>{location&&<dl><div><dt>{t('Latitude')}</dt><dd>{number(location.latitude,5)}</dd></div><div><dt>{t('Longitude')}</dt><dd>{number(location.longitude,5)}</dd></div><div><dt>{t('Accuracy (m)')}</dt><dd>{number(location.accuracy)}</dd></div><div><dt>{t('Speed')} ({unit})</dt><dd>{number(typeof location.speed==='number'&&location.speed>=0?location.speed*3.6/(unit==='mph'?1.609344:1):null)}</dd></div><div><dt>{t('Heading (°)')}</dt><dd>{number(location.heading)}</dd></div></dl>}</section></div><footer>{t('Not affiliated with Tesla. For display only.')}</footer></dialog>
}
